apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-email-worker
  ports:
    - port: {{ .Values.emailWorker.service.prometheusPort }}
      targetPort: {{ .Values.emailWorker.service.prometheusPort }}