apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mzinga-email: {{ required "emailWorker.credentials.email is required" .Values.emailWorker.credentials.email | quote }}
  mzinga-password: {{ required "emailWorker.credentials.password is required" .Values.emailWorker.credentials.password | quote }}